server:
  #启动关口
  port: 8000

spring:
  application:
    #服务名
    name: wuying-demo
  cloud:
    consul:
      #consul端口
      port: 8500
      #consul地址
      host: 127.0.0.1
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=CST
    username: root
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        #监控端点暴露
        include: info,health,metrics,prometheus

wuying:
  cloud:
    mybatis:
      support:
        #mybatis查询条数限制，默认10000
        maxRow: 2